pipeline{ 
    agent any

    stages{
        stage('Checkout'){
            steps{
                sh 'sleep 5'
            }
        }
        stage('Build'){
            steps{
                sh 'sleep 5'
            }
        }
        stage('Test'){
            steps{
                sh '''
                #!/bin/bash
                ls -lrt
                pwd
                sleep 5
                '''
                exit 1
            }
        }
        stage('Deploy'){
            steps{
                sh 'sleep 10'
            }
        }
    } 
}