pipeline{ 
    agent any

    stages{
        stage('Build'){
            step{
                sh 'sleep 5'
            }
        }
        stage('Test'){
            step{
                sh 'sleep 5'
            }
        }
    } 
}